/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 07 17:47:21 GMT 2026
 */

package br.ufjf.pos;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.pos.Calculadora;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculadora_ESTest extends Calculadora_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double[] doubleArray0 = new double[5];
      double double0 = calculadora0.multiplicar(doubleArray0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double[] doubleArray0 = new double[5];
      double double0 = calculadora0.somar(doubleArray0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      // Undeclared exception!
      try { 
        calculadora0.dividir(0.0, 0.0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // Divis\u00E3o por zero n\u00E3o permitida
         //
         verifyException("br.ufjf.pos.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double double0 = calculadora0.dividir((-1239.70751162386), (-1239.70751162386));
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double double0 = calculadora0.somar(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double double0 = calculadora0.multiplicar(1.0, 3251.69);
      assertEquals(3251.69, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double double0 = calculadora0.subtrair(2639.47, 27.0);
      assertEquals(2612.47, double0, 0.01);
  }
}
