/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 06 19:44:19 GMT 2026
 */

package br.ufjf.pos;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.pos.Calculadora;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculadora_ESTest extends Calculadora_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float[] floatArray0 = new float[2];
      float float0 = calculadora0.multiplicar(floatArray0);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float[] floatArray0 = new float[2];
      float float0 = calculadora0.somar(floatArray0);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      // Undeclared exception!
      try { 
        calculadora0.dividir(1292.4823F, 0.0F);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // Divis\u00E3o por zero n\u00E3o permitida
         //
         verifyException("br.ufjf.pos.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.dividir((-1116.5719F), 1227.0F);
      assertEquals((-0.9100016F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.multiplicar(0.0F, 0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.somar(0.0F, 0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.subtrair(0.0F, 0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }
}
