package br.ufjf.pos;/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 05 23:56:39 GMT 2026
 */

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculadora_ESTest extends Calculadora_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.subtrair(0.0F, 0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.subtrair(905.6F, 0.0F);
      assertEquals(905.6F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.somar((-588803.6F), 1909462.6F);
      assertEquals(1320659.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.somar((-588803.6F), 2240.6536F);
      assertEquals((-586563.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.multiplicar(852.19F, 2240.6536F);
      assertEquals(1909462.6F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.multiplicar(852.19F, (-690.93F));
      assertEquals((-588803.6F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.dividir(0.0F, 2748.2947F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.dividir(1.0F, (-586563.0F));
      assertEquals((-1.7048467E-6F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.multiplicar(0.0F, 0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.somar(0.0F, 0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.subtrair(0.0F, 1674.8739F);
      assertEquals((-1674.8739F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      float float0 = calculadora0.dividir((-3576.956F), (-1674.8739F));
      assertEquals(2.1356568F, float0, 0.01F);
  }
}